### PR TITLE
removed specimen.processingTime extension for FHIR-40950

### PR DESCRIPTION
**Pull request by jdlnolen**
Removed specimen.processingTime extension for FHIR-40950

### CODE REVIEW

**Comment by grahamegrieve** [comment]
I'm not sure about this. The extensions pack applies to all versions, so rather than remove it, you should mark in the documentation that this is no longer relevant for R6 since there's a matching element in R6 to use instead

**Comment by jdlnolen** [comment]
@grahamegrieve makes sense. I'll undo the delete and document the change. Thanks!

**Comment by jdlnolen** [comment]
See comments above.

**Comment by jdlnolen** [comment]
See comments above

**Pull request closed without merging**
