### PR TITLE
Patient admin/bp batch1 - new Standard extensions included

### PR DESCRIPTION
**Pull request by brianpos**
Batch of approved new PA standard extensions
FHIR-31505 Add Identity Unknown Extension to Patient
FHIR-17501 Patient Known Non Duplicate standard extension
FHIR-44603 Patient.contact add ranking
FHIR-34381 Add attribute to capture whether practitioner works part time, full time

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
order should indicate what it means if the order is the same, or if some repetitions have an order extension and some do not.

**Review by lmckenzi — COMMENTED** [review]
Could use a better explanation of what it means for a patient's identity to be known vs. unknown.  Some explanation that, yes they have an identifier (an MRN) and yes they may have a temporary pseudonym or even a partial name.  Does it mean you don't have official identification for tor them?  They can't identify themselves?

Pretty sure there's an existing code system that defines employment types.  Why are we defining a new one?

**Comment by brianpos** [comment]
> Could use a better explanation of what it means for a patient's identity to be known vs. unknown. Some explanation that, yes they have an identifier (an MRN) and yes they may have a temporary pseudonym or even a partial name. Does it mean you don't have official identification for tor them? They can't identify themselves?
> 
> Pretty sure there's an existing code system that defines employment types. Why are we defining a new one?

Is this the one that you are thinking of?
Looks pretty wacky the ... concept.
https://terminology.hl7.org/CodeSystem-v2-0066.html

**Review by lmckenzi — APPROVED** [review]
ok.  Would still like to see my other concerns addressed

**Pull request merged**
