### PR TITLE
Added extensions from CRMI IG

### PR DESCRIPTION
**Pull request by brynrhodes**
J#41625: Add the extensions currently defined in the CRMI IG to the base specification so that they can be referenced by any IG:

https://build.fhir.org/ig/HL7/crmi-ig/artifacts.html#4

Specifically, add:
Artifact Approval Date
Artifact Assesssment Content
Artifact Assessment Disposition
Artifact Assessment Workflow Status
Artifact Canonical Reference
Artifact Cite As
Artifact Comment
Artifact Effective Period
Artifact Is Owned
Artifact Last Review Date
Artifact REference
Artifact Release Description
Artifact Release Label
Artifact Usage
Artifact Version Policy
Default Value
Definition Term
Expansion Parameters
FHIR Query Pattern
Is Primary Citation
Is Selective
Messages
ModelInfo Is Included
ModelInfo Is Retrievable
ModelInfo Label
ModelInfo Primary Code Path
ModelInfo Settings
Not Done ValueSet
Part Of
Publication Date
Publication Status
Resource Type
Scope
Value Filter

### CODE REVIEW

**Comment by grahamegrieve** [comment]
The extensions that belong on resource should be in the /resource subfolder, and any others that don't go on Element should not be in the /element folder

**Comment by brynrhodes** [comment]
It looks like several of the existing artifact-xxx extensions are targeting Element and really shouldn't be, should I fix those as part of this?

**Comment by brynrhodes** [comment]
Note that I also fixed the existing versionAlgorithm extension as a technical correction, the fixed url was pointing at version and it didn't have the Coding option bound to the versionAlgorithm value set.

**Review by grahamegrieve — COMMENTED** [review]
shouldn't we fix the context for most of the artefact* extensions in Element? versionAlgorithm, for instance?

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
