### PR TITLE
Ti extension changes 1

### PR DESCRIPTION
**Pull request by MLD1995**
FHIR-40702, FHIR-40719, FHIR-40707, FHIR-40740, FHIR-40718, FHIR-40705, FHIR-40704, FHIR-40717, FHIR-40710, FHIR-40715, FHIR-40732, FHIR-40741, FHIR-40706, FHIR-40730, FHIR-40739, FHIR-45254, FHIR-40731, FHIR-40712, FHIR-40711, FHIR-40716, FHIR-40737, FHIR-39326, and FHIR-40733

### CODE REVIEW

**Review by lmckenzi — CHANGES_REQUESTED** [review]
If you're deprecating or retiring things, you should update the documentation to indicate what should be used instead.

Changing the data type of valueset-compose-createdBy is against the rules.  You can add types or deprecate and define a new extension.  For createionDate, it's a clear error, so less of an issue.

You can't delete extensions.  You have to deprecate/retire them.

**Comment by MLD1995** [comment]
For the ones where the extension was removed, does the fact that it was the FHIR product director requesting that TI remove them change anything?  We would have gone with retirement but since Grahame requested removal for those ones instead of retirement we did that instead.  If not, I can pull them and get TI to revisit what to do with them.

**Review by lmckenzi — APPROVED** [review]
StructureDefinition-codesystem-use-markdown.xml doesn't have a deprecation reason

**Review by grahamegrieve — APPROVED** [review]
ok

**Pull request merged**
