### PR TITLE
Remove Composition's version# and otherConf extensions

### PR DESCRIPTION
**Pull request by benjaminflessner**
Removing two ClinicalDocument extensions because they are obsolete now with updates to Composition in R5.

https://jira.hl7.org/browse/FHIR-37719
https://jira.hl7.org/browse/FHIR-38201

### CODE REVIEW

**Review by lmckenzi — COMMENTED** [review]
Is there a need for these extensions still in R4 or earlier releases?

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by grahamegrieve** [comment]
@benjaminflessner do you want to fix the conflicts, or resubmit without those files?

**Review by grahamegrieve — APPROVED** [review]
ok

**Comment by grahamegrieve** [comment]
I'm closing this. @benjaminflessner if you still want to do something with these, resubmit. But they look like candidates for deprecation not removal to me .

**Pull request closed without merging**
